version: "3.9"
services:

  front_nginx_server:
    container_name: front-nginx-server 
    image: nginx:latest 
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf 
    ports:
      - "8010:80"
    depends_on:
      - front_application 
    networks:
      - cloud-infrastructure-network 

  front_application:
    container_name: front_application_server 
    image: crazycoderrr/cloud-infrastructure-front-app 
    ports:
      - "8080:8080"
    networks:
      - cloud-infrastructure-network 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5

  stripe_payment_service:
    - container_name: stripe-application-service 
      build: ../webhooks/.
      ports:
        - "8001:8001"
      healthcheck:
        test: ["curl", "-f", "http://localhost:8001"]
        retries: 5 
        timeout: 10 
        start_period: 10
      networks:
        - cloud-infrastructure-network

  crypto_smart_contract_deployer: 
    - container_name: smart-contract-deployer 
      image: ethereum/sol 
      ports:
        - "4000:4000"
      networks:
        - cloud-infrastructure-network 

networks:
  cloud-infrastructure-network:
      external: true 
      name: "cloud-infrastructure-network"
