version: "3.9"
services:

  front_nginx_server:
    container_name: front-nginx-server 
    image: nginx:latest 
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf 
    ports:
      - "8010:80"
    depends_on:
      - front_application 
    networks:
      - cloud-infrastructure-network 

  front_application:
    container_name: front_application_server 
    image: crazycoderrr/cloud-infrastructure-front-app 
    ports:
      - "8080:8080"
    env_file: ../env/project.env
    networks:
      - cloud-infrastructure-network 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]

  stripe_payment_service:
    container_name: stripe-application-service 
    build: ../src/webhooks/.
    ports:
      - "8001:8001"
    env_file: ../env/project.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001"]
    networks:
      - cloud-infrastructure-network

networks:
  cloud-infrastructure-network:
      external: true 
      name: "cloud-infrastructure-network"
