apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: app-namespace
spec:
  selector:
    app: front-app
  ports:
    - name: http
      port: 3000
      protocol: TCP
---

apiVersion: v1
kind: Deployment
metadata:
  name: front-application
  namespace: app-namespace
spec:
  selector:
    matchLabels:
      app: front-app
  templates:
    metadata:
      labels:
        app: front-app
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: front-app-container
          image: crazycoderrr/infrastructure_front_app
          ports:
            - containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                - name: front-app-config-map
          imagePullPolicy: Always

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: front-app-config-map
  namespace: app-namespace
data:
  BACKEND_APPLICATION_HOST: infrastructure.app-namespace.svc.cluster.local:8000
  BACKEND_APPLICATION_PORT: 8000
